on: [pull_request]

jobs:
  test:
    name: Test on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os:
          - ubuntu-latest
          # - ubuntu-24.04-arm
          # - windows-latest
          # - windows-11-arm
          # - macos-13
          # - macos-latest

    steps:
      - uses: fortran-lang/setup-fortran@v1
      - uses: astral-sh/setup-uv@v5
      - uses: actions/checkout@v4
      - run: |
          uv venv --default-index https://pypi.org/simple
          uv sync --default-index https://pypi.org/simple
          uv run pytest -vv -s
        shell: bash -el {0}