on: [pull_request]

jobs:
  test:
    name: Test on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os:
          - ubuntu-latest
          - ubuntu-24.04-arm
          - windows-latest
          - windows-11-arm
          - macos-13
          - macos-latest

    steps:
      - uses: actions/checkout@v4
      - uses: astral-sh/setup-uv@v5
      - uses: fortran-lang/setup-fortran@v1
        with:
          compiler: gcc
          version: 13
      - run: |
          uv venv --default-index
          uv sync --default-index
          uv run pytest -vv -s
        shell: bash -el {0}