name: Build & Test

on:
  pull_request:

jobs:
  build_wheels:
    name: Build wheels for cp${{ matrix.python }}-${{ matrix.platform_id }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        include:
          - os: ubuntu-latest
            python: 312
            platform_id: manylinux_x86_64
          - os: macos-14
            python: 312
            platform_id: macosx_arm64
          - os: windows-latest
            python: 312
            platform_id: win_amd64
    steps:
      - uses: fortran-lang/setup-fortran@v1
      - uses: actions/checkout@v4
      - uses: pypa/cibuildwheel@v3.1.1
        env:
          CIBW_BUILD_VERBOSITY: 1
          CIBW_ARCHS: all
          CIBW_BUILD: cp${{ matrix.python }}-${{ matrix.platform_id }}
      - run: ls -l wheelhouse/*
