name: Build & Test

on:
  pull_request:

jobs:
  build_wheels:
    name: Build wheels for cp${{ matrix.python }}-${{ matrix.platform_id }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        include:
          # - os: ubuntu-latest
          #   python: 312
          #   platform_id: manylinux_x86_64
          # - os: macos-latest
          #   python: 312
          #   platform_id: macosx_arm64
          #   macos_target: 14
          - os: windows-latest
            python: 312
            platform_id: win_amd64

    steps:
      - name: Provide gfortran (MacOS)
        uses: fortran-lang/setup-fortran@v1
        if: runner.os == 'MacOS'
        with:
          compiler: gcc
      - name: Provide gfortran (Windows)
        # https://github.com/actions/runner-images/discussions/7998
        uses: msys2/setup-msys2@v2
        with:
          update: true
          install: >-
            mingw-w64-ninja
            mingw-w64-openblas
      - uses: actions/checkout@v4
      - uses: astral-sh/setup-uv@v5
      - uses: pypa/cibuildwheel@v3.1.1
        env:
          CIBW_ARCHS: all
          CIBW_BUILD_VERBOSITY: 1
          CIBW_BEFORE_ALL_MACOS: "brew install openblas"
          CIBW_BEFORE_ALL_LINUX: "yum install -y openblas-devel"
          CIBW_ENVIRONMENT_WINDOWS: SKBUILD_CMAKE_ARGS='-GNinja'
          CIBW_BUILD: cp${{ matrix.python }}-${{ matrix.platform_id }}
          # MACOSX_DEPLOYMENT_TARGET: ${{ matrix.macos_target }}.0
      - run: ls -l wheelhouse/*
