name: Build & Test

on:
  pull_request:

jobs:
  build_wheels:
    name: Build wheels for cp${{ matrix.python }}-${{ matrix.platform_id }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        include:
          - os: ubuntu-latest
            python: 312
            platform_id: manylinux_x86_64
          - os: macos-latest
            python: 312
            macos_target: 14
            platform_id: macosx_arm64
          - os: macos-13
            python: 312
            macos_target: 13
            platform_id: macosx_x86_64
    steps:
      - name: Provide gfortran (MacOS)
        uses: fortran-lang/setup-fortran@v1
        if: runner.os == 'MacOS'
        with:
          compiler: gcc
      - uses: actions/checkout@v4
      - uses: astral-sh/setup-uv@v5
      - uses: pypa/cibuildwheel@v3.1.1
        env:
          CIBW_ARCHS: all
          CIBW_BUILD_VERBOSITY: 1
          CIBW_BEFORE_ALL_LINUX: "yum install -y openblas-devel"
          CIBW_BEFORE_ALL_MACOS: "brew install --overwrite openblas"
          CIBW_BUILD: cp${{ matrix.python }}-${{ matrix.platform_id }}
          MACOSX_DEPLOYMENT_TARGET: ${{ matrix.macos_target }}.0
      - run: ls -l wheelhouse/*

  build_wheels_for_windows:
    name: Build wheels for cp${{ matrix.python }}-${{ matrix.platform_id }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        include:
          - os: windows-latest
            python: 312
            platform_id: win_amd64
    steps:
      - name: Provide gfortran (Windows)
        # https://github.com/actions/runner-images/discussions/7998
        uses: msys2/setup-msys2@v2
        if: runner.os == 'Windows'
        id: msys2
        with:
          update: true
          cache: true
          path-type: inherit
          install: >-
            mingw-w64-x86_64-openblas
            mingw-w64-x86_64-gcc-fortran
      - uses: actions/checkout@v4
      - uses: astral-sh/setup-uv@v5
      - name: Build wheels (Windows)
        run: |
          uv python pin cpython{{ matrix.python }}
          uv build --wheel
          dir dist/*
      - name: Repair wheels (Windows)
        run: |
          pipx run delvewheel repair dist/*.whl -vv
          dir wheelhouse
      - name: Test wheels (Windows)
        run: |
          uv pip install wheelhouse/*.whl pytest
          python -m pytest -s -vv