on: [pull_request]

jobs:
  test:
    name: Test on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os:
          - ubuntu-latest
          # - ubuntu-24.04-arm
          # - windows-latest
          # - windows-11-arm
          # - macos-13
          # - macos-latest

    steps:
      - uses: actions/checkout@v4
      - name: Build wheels
        run: pipx run cibuildwheel==3.1.1
      - uses: actions/upload-artifact@v4
        with:
          name: cibw-wheels-${{ matrix.os }}-${{ strategy.job-index }}
          path: ./wheelhouse/*.whl

      # - uses: mamba-org/setup-micromamba@v2
      #   with:
      #     environment-name: wheel
      #     condarc: |
      #       channels:
      #         - conda-forge
      #         - pytorch
      #     create-args: >-
      #       c-compiler
      #       fortran-compiler
      #       libopenblas
      # - uses: astral-sh/setup-uv@v5
      # - uses: actions/checkout@v4
      # - run: |
      #     uv venv --default-index https://pypi.org/simple
      #     uv sync --default-index https://pypi.org/simple
      #     uv run pytest -vv -s
      #   shell: bash -el {0}