on: [pull_request]

jobs:
  test:
    name: Test on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os:
          - ubuntu-latest
          # - ubuntu-24.04-arm
          # - windows-latest
          # - windows-11-arm
          # - macos-13
          # - macos-latest

    steps:
      - uses: actions/checkout@v4
      - uses: astral-sh/setup-uv@v5
      - uses: fortran-lang/setup-fortran@v1
      - run: |
          uv sync
          uv build --wheel
          uv pip install pytest
          uv pip install dist/*whl
          source .venv/bin/activate
          pytest -s
        shell: bash -el {0}